# Generated by Django 2.2.4 on 2019-08-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190824_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderschedule',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='serviceproviderschedule',
            name='time_start',
        ),
    ]
