# Generated by Django 2.2.4 on 2019-08-24 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190824_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderschedule',
            name='time_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='serviceproviderschedule',
            name='time_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
